### ISSUE TITLE
添加菜单的时候报错

### ISSUE THREAD

**Issue by tianchengli** [willerce/canku#24]
我部署到我的server上，但偶尔情况下，添加菜单的时候报错，报错内容如下：

<pre>
POST /admin/food/add?shop_id=521c17f7f5673b0468000002 302 7ms - 152b
{ '0': '星期天',
  '1': '星期一',
  '2': '星期二',
  '3': '星期三',
  '4': '星期四',
  '5': '星期五',
  '6': '星期六',
  '-1': '全部' }
GET /admin/food/add?shop_id=521c17f7f5673b0468000002 200 26ms

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: socket hang up
    at createHangUpError (http.js:1360:15)
    at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
    at ServerResponse.OutgoingMessage._send (http.js:476:15)
    at ServerResponse.OutgoingMessage.end (http.js:890:18)
    at ServerResponse.module.exports.res.end (/home/litc/test/canku/node_modules/express/node_modules/connect/lib/middleware/logger.js:148:13)
    at ServerResponse.module.exports.res.end (/home/litc/test/canku/node_modules/express/node_modules/connect/lib/middleware/compress.js:123:15)
    at res.end (/home/litc/test/canku/node_modules/express/node_modules/connect/lib/middleware/session.js:285:13)
    at /home/litc/test/canku/node_modules/express/node_modules/connect/lib/middleware/session/memory.js:73:11
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

</pre>

不知道是怎么回事，大家给看看。

**Comment by willerce** [comment]
看着似乎是在写入流时出现的问题，目测不是 canku 的原因，尝试更新一下 nodejs 以及 expressjs
